<?php

declare(strict_types=1);

return [
    'routes' => [
        ['name' => 'thumbnail_settings#save', 'url' => '/admin/thumbnails', 'verb' => 'POST'],
        ['name' => 'scan_schedule#save', 'url' => '/scan/schedule', 'verb' => 'POST'],
        ['name'=>'duplicate_suggestion#status','url'=>'/api/duplicate-suggestions','verb'=>'GET'],
        ['name'=>'duplicate_suggestion#configure','url'=>'/api/duplicate-suggestions','verb'=>'POST'],
        ['name'=>'duplicate_suggestion#lookup','url'=>'/api/duplicate-suggestions/lookup','verb'=>'POST'],
        ['name'=>'duplicate_suggestion#compare','url'=>'/api/duplicate-suggestions/compare/{leftId}/{rightId}','verb'=>'GET'],
        ['name'=>'duplicate_suggestion#decide','url'=>'/api/duplicate-suggestions/compare/{leftId}/{rightId}','verb'=>'POST'],
        ['name'=>'duplicate_suggestion#settings','url'=>'/duplicate-suggestions/settings','verb'=>'POST'],
        ['name'=>'duplicate#index','url'=>'/api/duplicates','verb'=>'GET'],
        ['name'=>'duplicate#start','url'=>'/api/duplicates','verb'=>'POST'],
        ['name'=>'duplicate#show','url'=>'/api/duplicates/{scanId}','verb'=>'GET'],
        ['name'=>'duplicate#advance','url'=>'/api/duplicates/{scanId}/advance','verb'=>'POST'],
        ['name'=>'duplicate#cancel','url'=>'/api/duplicates/{scanId}/cancel','verb'=>'POST'],
        ['name'=>'duplicate#discard','url'=>'/api/duplicates/{scanId}/discard','verb'=>'POST'],
        ['name'=>'duplicate#decide','url'=>'/api/duplicates/{scanId}/pairs/{pairId}','verb'=>'POST'],
        ['name'=>'inference_analysis#index','url'=>'/api/inference/analyses','verb'=>'GET'],
        ['name'=>'inference_analysis#start','url'=>'/api/inference/analyses','verb'=>'POST'],
        ['name'=>'inference_analysis#show','url'=>'/api/inference/analyses/{analysisId}','verb'=>'GET'],
        ['name'=>'inference_analysis#advance','url'=>'/api/inference/analyses/{analysisId}/advance','verb'=>'POST'],
        ['name'=>'inference_analysis#cancel','url'=>'/api/inference/analyses/{analysisId}/cancel','verb'=>'POST'],
        ['name'=>'inference_analysis#discard','url'=>'/api/inference/analyses/{analysisId}/discard','verb'=>'POST'],
        ['name' => 'inference_batch#index', 'url' => '/api/inference/batches', 'verb' => 'GET'],
        ['name' => 'inference_batch#prepare', 'url' => '/api/inference/batches', 'verb' => 'POST'],
        ['name' => 'inference_batch#show', 'url' => '/api/inference/batches/{batchId}', 'verb' => 'GET'],
        ['name' => 'inference_batch#apply', 'url' => '/api/inference/batches/{batchId}/apply', 'verb' => 'POST'],
        ['name' => 'inference_batch#undo', 'url' => '/api/inference/batches/{batchId}/undo', 'verb' => 'POST'],
        ['name' => 'inference_batch#discard', 'url' => '/api/inference/batches/{batchId}/discard', 'verb' => 'POST'],

        ['name' => 'page#index', 'url' => '/', 'verb' => 'GET'],
        ['name' => 'page#catalogue', 'url' => '/catalogue', 'verb' => 'GET'],
        ['name' => 'page#shelfChildren', 'url' => '/shelves/children', 'verb' => 'GET'],
        ['name' => 'page#publicationSuggestions', 'url' => '/catalogue/publication-suggestions', 'verb' => 'GET'],
        ['name' => 'page#creatorSuggestions', 'url' => '/catalogue/creator-suggestions', 'verb' => 'GET'],
        ['name' => 'page#publisherSuggestions', 'url' => '/catalogue/publisher-suggestions', 'verb' => 'GET'],
        ['name' => 'page#subjectSuggestions', 'url' => '/catalogue/subject-suggestions', 'verb' => 'GET'],
        ['name' => 'page#classificationSuggestions', 'url' => '/catalogue/classification-suggestions', 'verb' => 'GET'],
        ['name' => 'page#tagSuggestions', 'url' => '/catalogue/tag-suggestions', 'verb' => 'GET'],
        ['name' => 'page#folderSuggestions', 'url' => '/catalogue/folder-suggestions', 'verb' => 'GET'],
        ['name' => 'page#yearSuggestions', 'url' => '/catalogue/year-suggestions', 'verb' => 'GET'],
        ['name' => 'page#publication', 'url' => '/publications/{publication}', 'verb' => 'GET', 'requirements' => ['publication' => '.+']],
        ['name' => 'page#year', 'url' => '/years/{year}', 'verb' => 'GET'],
        ['name' => 'page#creator', 'url' => '/creators/{creator}', 'verb' => 'GET', 'requirements' => ['creator' => '.+']],
        ['name' => 'root#save', 'url' => '/roots', 'verb' => 'POST'],
        ['name' => 'root#update', 'url' => '/roots/{rootId}', 'verb' => 'POST'],
        ['name' => 'root#toggle', 'url' => '/roots/{rootId}/toggle', 'verb' => 'POST'],
        ['name' => 'root#delete', 'url' => '/roots/{rootId}/delete', 'verb' => 'POST'],
        ['name' => 'scan#run', 'url' => '/scan', 'verb' => 'POST'],
        ['name' => 'scan#runRoot', 'url' => '/scan/roots/{rootId}', 'verb' => 'POST'],
        ['name' => 'scan#retryMetadataErrors', 'url' => '/scan/retry-metadata-errors', 'verb' => 'POST'],
        ['name' => 'scan#recheckMissingFiles', 'url' => '/scan/recheck-missing-files', 'verb' => 'POST'],
        ['name' => 'scan#cancel', 'url' => '/scan/jobs/{jobId}/cancel', 'verb' => 'POST'],
        ['name' => 'scan#progress', 'url' => '/scan/progress', 'verb' => 'GET'],
        ['name' => 'export#metadata', 'url' => '/export/metadata', 'verb' => 'GET'],
        ['name' => 'health#importSummary', 'url' => '/health/import-summary', 'verb' => 'GET'],
        ['name' => 'health#refreshImportSummary', 'url' => '/health/import-summary', 'verb' => 'POST'],
        ['name' => 'health#metadataErrors', 'url' => '/health/metadata-errors', 'verb' => 'GET'],
        ['name' => 'health#metadataErrorsTsv', 'url' => '/health/metadata-errors.tsv', 'verb' => 'GET'],
        ['name' => 'health#coverProbe', 'url' => '/health/covers/probe', 'verb' => 'POST'],
        ['name' => 'export#sidecarManifest', 'url' => '/export/metadata/sidecar-manifest', 'verb' => 'GET'],
        ['name' => 'export#sidecarBundle', 'url' => '/export/metadata/sidecars.zip', 'verb' => 'GET'],
        ['name' => 'import#preview', 'url' => '/import/metadata/preview', 'verb' => 'POST'],
        ['name' => 'import#apply', 'url' => '/import/metadata/apply', 'verb' => 'POST'],
        ['name' => 'saved_collection#save', 'url' => '/collections', 'verb' => 'POST'],
        ['name' => 'inference_pattern#index', 'url' => '/api/inference/patterns', 'verb' => 'GET'],
        ['name' => 'inference_pattern#create', 'url' => '/api/inference/patterns', 'verb' => 'POST'],
        ['name' => 'inference_pattern#delete', 'url' => '/api/inference/patterns/{patternId}/delete', 'verb' => 'POST', 'requirements' => ['patternId' => '(?:[a-f0-9]{32}|preset-[a-z-]{1,64})']],
        ['name' => 'inference_folder_rule#index', 'url' => '/api/inference/folders', 'verb' => 'GET'],
        ['name' => 'inference_folder_rule#create', 'url' => '/api/inference/folders', 'verb' => 'POST'],
        ['name' => 'inference_folder_rule#delete', 'url' => '/api/inference/folders/{assignmentId}/delete', 'verb' => 'POST', 'requirements' => ['assignmentId' => '[a-f0-9]{32}']],
        ['name' => 'inference#sample', 'url' => '/api/inference/sample', 'verb' => 'GET'],
        ['name' => 'personal_list#index', 'url' => '/api/lists', 'verb' => 'GET'],
        ['name' => 'personal_list#create', 'url' => '/api/lists', 'verb' => 'POST'],
        ['name' => 'personal_list#show', 'url' => '/api/lists/{listId}', 'verb' => 'GET', 'requirements' => ['listId' => '[1-9][0-9]*']],
        ['name' => 'personal_list#action', 'url' => '/api/lists/{listId}/actions', 'verb' => 'POST', 'requirements' => ['listId' => '[1-9][0-9]*']],
        ['name' => 'saved_collection#delete', 'url' => '/collections/{collectionId}/delete', 'verb' => 'POST'],
        ['name' => 'tag#batchassign', 'url' => '/bulk/tags', 'verb' => 'POST'],
        ['name' => 'tag#batchremove', 'url' => '/bulk/tags/remove', 'verb' => 'POST'],
        ['name' => 'item#batchresetfilteredfields', 'url' => '/bulk/items/reset-filtered-fields', 'verb' => 'POST'],
        ['name' => 'item#batchpreviewmetadataedit', 'url' => '/bulk/items/edit-preview', 'verb' => 'POST'],
        ['name' => 'item#batchapplymetadataedit', 'url' => '/bulk/items/edit-apply', 'verb' => 'POST'],
        ['name' => 'cover#batchrefresh', 'url' => '/bulk/covers/refresh', 'verb' => 'POST'],
        ['name' => 'item_page#sidebar', 'url' => '/items/{itemId}/sidebar', 'verb' => 'GET', 'requirements' => ['itemId' => '[^/]+']],
        ['name' => 'item_page#show', 'url' => '/items/{itemId}', 'verb' => 'GET', 'requirements' => ['itemId' => '[1-9][0-9]*']],
        ['name' => 'item#resetfield', 'url' => '/items/{itemId}/reset-field', 'verb' => 'POST'],
        ['name' => 'item#resetfields', 'url' => '/items/{itemId}/reset-fields', 'verb' => 'POST'],
        ['name' => 'item#open', 'url' => '/items/{itemId}/open', 'verb' => 'GET'],
        ['name' => 'item#recordOpen', 'url' => '/items/{itemId}/open', 'verb' => 'POST'],
        ['name' => 'item#update', 'url' => '/items/{itemId}', 'verb' => 'POST'],
        ['name' => 'item#star', 'url' => '/items/{itemId}/star', 'verb' => 'POST'],
        ['name' => 'item#workflowStatus', 'url' => '/items/{itemId}/workflow-status', 'verb' => 'POST'],
        ['name' => 'item#forgetMissing', 'url' => '/items/{itemId}/forget-missing', 'verb' => 'POST'],
        ['name' => 'cover#show', 'url' => '/items/{itemId}/cover', 'verb' => 'GET'],
        ['name' => 'cover#override', 'url' => '/items/{itemId}/cover/override', 'verb' => 'POST'],
        ['name' => 'cover#revert', 'url' => '/items/{itemId}/cover/revert', 'verb' => 'POST'],
        ['name' => 'tag#assign', 'url' => '/items/{itemId}/tags', 'verb' => 'POST'],
        ['name' => 'tag#remove', 'url' => '/items/{itemId}/tags/{tagId}', 'verb' => 'POST'],
        ['name' => 'comment#add', 'url' => '/items/{itemId}/comments', 'verb' => 'POST'],
    ],
];
