<script setup>
import { ref,onMounted,onBeforeUnmount } from 'vue'
import { t } from '@nextcloud/l10n'
import { generateUrl } from '@nextcloud/router'
import LabelHelp from './LabelHelp.vue'
const props=defineProps({requestToken:String});const state=ref({enabled:false,status:'disabled'}),busy=ref(false),error=ref('');let alive=true,timer
async function load(){try{const response=await fetch(generateUrl('/apps/library/api/duplicate-suggestions'),{cache:'no-store',credentials:'same-origin'});if(!response.ok)throw new Error();const data=await response.json();if(alive){state.value=data;if(data.status==='building')timer=setTimeout(load,5000)}}catch{if(alive)error.value=t('library','Could not complete the duplicate review. Please try again.')}}
async function toggle(event){busy.value=true;error.value='';clearTimeout(timer);try{const response=await fetch(generateUrl('/apps/library/api/duplicate-suggestions'),{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json',requesttoken:props.requestToken},body:JSON.stringify({enabled:event.target.checked})});if(!response.ok)throw new Error();state.value=await response.json();if(state.value.status==='building')timer=setTimeout(load,2000)}catch{error.value=t('library','Could not complete the duplicate review. Please try again.')}finally{busy.value=false}}
onMounted(load);onBeforeUnmount(()=>{alive=false;clearTimeout(timer)})
</script>
<template><section class="library-auto-duplicate-settings" :aria-busy="busy?'true':'false'"><label><input type="checkbox" :checked="state.enabled" :disabled="busy" @change="toggle"><LabelHelp :text="t('library','Build a private metadata index in the background. Suggestions check the whole library without reading book contents.')">{{ t('library','Show possible duplicates while browsing') }}</LabelHelp></label><p v-if="error" role="alert">{{ error }}</p><p v-if="state.status==='building'" role="status">{{ t('library','Indexing metadata') }} · {{ state.processed }}/{{ state.total }}</p><p v-if="state.status==='failed'" role="alert">{{ t('library','Duplicate scan failed') }}</p><p v-if="state.status==='ready'" role="status">{{ t('library','Automatic duplicate suggestions are ready.') }}</p></section></template>
<style>.library-auto-duplicate-settings{padding:16px;border:1px solid var(--color-border);border-radius:10px;margin-block:20px}.library-duplicates .library-auto-duplicate-settings label{display:flex;align-items:center;gap:8px}.library-auto-duplicate-settings input[type=checkbox]{flex:0 0 20px;width:20px;height:20px;min-width:20px;min-height:20px;margin:0}</style>
