<?php
/** Owned fixture account: scalar isolation, deterministic warning cache, forced retry and legacy adoption. */
declare(strict_types=1);define('OC_CONSOLE',true);require '/var/www/html/lib/base.php';
$uid='library-warning-smoke-'.bin2hex(random_bytes(6));$account=null;$checks=0;$failed=false;
function warningCheck(bool $value,string $message):void{global $checks;if(!$value)throw new RuntimeException($message);$checks++;}
function warningOpf(string $title,string $subtitle=''):string{return '<package xmlns="http://www.idpf.org/2007/opf"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>'.htmlspecialchars($title,ENT_XML1).'</dc:title><dc:description>Valid description</dc:description><dc:publisher>Fixture press</dc:publisher><dc:language>en</dc:language></metadata><meta name="unused" content="fixture"/></package>';}
try{
 $db=\OC::$server->get(\OCP\IDBConnection::class);$account=\OC::$server->get(\OCP\IUserManager::class)->createUser($uid,bin2hex(random_bytes(24)));$home=\OC::$server->get(\OCP\Files\IRootFolder::class)->getUserFolder($uid);$folder=$home->newFolder('Warning fixture');
 $pdf=$folder->newFile('oversized.pdf',"%PDF-1.4\nFixture\n%%EOF");$side=$folder->newFile('oversized.opf',warningOpf(str_repeat('É',920)));$bad=$folder->newFile('bad.cbz','Not an archive');$good=$folder->newFile('stable.opf',warningOpf('Stable title'));
 $roots=\OC::$server->get(\OCA\Library\Service\RootService::class);$root=$roots->saveRoot($uid,'/Warning fixture','Warning fixture',true);$scanner=\OC::$server->get(\OCA\Library\Service\LibraryScanner::class);$items=\OC::$server->get(\OCA\Library\Service\ItemService::class);$index=\OC::$server->get(\OCA\Library\Service\FileIndexService::class);
 $item=function($file)use($db,$uid){$r=$db->executeQuery('SELECT i.* FROM *PREFIX*library_items i INNER JOIN *PREFIX*library_files f ON f.id=i.library_file_id WHERE i.user_id=? AND f.file_id=?',[$uid,$file->getId()]);$v=$r->fetch();$r->closeCursor();return $v;};
 $first=$scanner->scan($uid,(int)$root['id']);warningCheck($first['metadataErrors']===2,'Scalar and archive warnings visible');$p=$item($pdf);warningCheck($p!==false,'Oversized book imported');warningCheck($p['title']==='oversized','Filename fallback title');warningCheck($p['publisher']==='Fixture press','Other valid fields retained');$values=json_decode($p['field_values'],true);warningCheck($values['title']===str_repeat('É',920),'Complete rejected Unicode proposal retained');warningCheck(json_decode($values['rejectedFields'],true)===['title'],'Rejected field explicitly recorded');
 $obs=$index->findByFileId($uid,$pdf->getId());warningCheck($obs['metadataExtractorRevision']==='metadata-pipeline-v7'&&$obs['metadataInputFingerprint']!==null,'Successful warning stores marker');$error=$obs['scanError'];
 $second=$scanner->scan($uid,(int)$root['id']);warningCheck($second['metadataExtractions']===0,'Unchanged warnings do not extract');warningCheck($second['cachedWarningSkips']===2,'Cached warnings counted separately');warningCheck($second['metadataErrors']===2,'Warnings stay visible');warningCheck($index->findByFileId($uid,$pdf->getId())['scanError']===$error,'Diagnostic retained unchanged');
 $retry=$scanner->retryMetadataErrors($uid);warningCheck($retry['metadataExtractions']===2,'Explicit Retry bypasses warning cache');warningCheck($retry['cachedWarningSkips']===0,'Forced retry not reported as cache hit');
 $side->putContent(warningOpf('Accepted title'));$changed=$scanner->scan($uid,(int)$root['id']);warningCheck($changed['metadataExtractions']===1,'Changed sidecar invalidates cache');warningCheck($item($pdf)['title']==='Accepted title','Valid correction imported');warningCheck($index->findByFileId($uid,$pdf->getId())['scanStatus']==='indexed','Resolved warning clears');
 $side->putContent(warningOpf(str_repeat('x',513)));$scanner->scan($uid,(int)$root['id']);warningCheck($item($pdf)['title']==='Accepted title','Previously accepted value retained');
 $items->applyBatchMetadataEdit($uid,[(int)$p['id']],'title','My correction');$side->putContent(warningOpf(str_repeat('x',514)));$scanner->scan($uid,(int)$root['id']);warningCheck($item($pdf)['title']==='My correction','Manual correction protected');
 $rejected=false;try{$items->resetFieldToScannerCandidate($uid,(int)$p['id'],'title');}catch(InvalidArgumentException){$rejected=true;}warningCheck($rejected,'Rejected proposal cannot bypass editor field limits');
 $saved=$index->findByFileId($uid,$good->getId());$db->executeStatement('UPDATE *PREFIX*library_files SET metadata_extractor_revision=? WHERE user_id=? AND file_id=?',['metadata-pipeline-v6',$uid,$good->getId()]);$adopt=$scanner->scan($uid,(int)$root['id']);warningCheck($adopt['metadataExtractions']===0,'Validated unchanged v6 metadata adopted without extraction');warningCheck($index->findByFileId($uid,$good->getId())['metadataExtractorRevision']==='metadata-pipeline-v7','Adopted revision recorded');
 $db->executeStatement('UPDATE *PREFIX*library_files SET scan_status=?,scan_error=? WHERE user_id=? AND file_id=?',['metadata_error','metadata_extraction_failed: Temporary read failure. (diagnostic: libdiag-0123456789abcdef)',$uid,$good->getId()]);$transient=$scanner->scan($uid,(int)$root['id']);warningCheck($transient['metadataExtractions']===1,'Transient failure never cached even with matching marker');
 $missing=$item($bad);$db->executeStatement('DELETE FROM *PREFIX*library_items WHERE user_id=? AND id=?',[$uid,(int)$missing['id']]);$repair=$scanner->scan($uid,(int)$root['id']);warningCheck($repair['metadataExtractions']===1&&$item($bad)!==false,'Missing catalogue item repairs instead of cache skip');
 $bytes=hash('sha256',$pdf->getContent());$scanner->scan($uid,(int)$root['id']);warningCheck(hash('sha256',$pdf->getContent())===$bytes,'Source bytes unchanged');
 $jobs=\OC::$server->get(\OCA\Library\Service\ScanJobService::class);$job=$jobs->startJob($uid);$result=$scanner->scan($uid,(int)$root['id']);$jobs->finishJob($uid,$job['id'],$result);warningCheck($jobs->getJob($uid,$job['id'])['cachedWarningSkips']===2,'Warning cache hits survive job history persistence');
 echo json_encode(['passed'=>true,'assertions'=>$checks,'sourceBytesUnchanged'=>true]),PHP_EOL;
}catch(Throwable $e){$failed=true;fwrite(STDERR,get_class($e).': '.$e->getMessage().PHP_EOL);}finally{if($account)$account->delete();echo json_encode(['cleanup'=>true]),PHP_EOL;}if($failed)exit(1);
