<?php
/** Real Files/scanner checks in an owned disposable account; fail closed and clean up. */
declare(strict_types=1);define('OC_CONSOLE',true);require '/var/www/html/lib/base.php';require '/tmp/library-performance-sql-profiler.php';
$uid='library-index-smoke-'.bin2hex(random_bytes(6));$account=null;$checks=0;$failed=false;
function indexCheck(bool $value,string $message):void{global $checks;if(!$value)throw new RuntimeException($message);$checks++;}
function indexOpf(string $title,string $author='García, Ana',string $isbn='9780306406157'):string{return '<package xmlns="http://www.idpf.org/2007/opf"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>'.$title.'</dc:title><dc:creator>'.$author.'</dc:creator><dc:subject>Écologie</dc:subject><dc:publisher>Fixture press</dc:publisher><dc:language>en</dc:language><dc:identifier>'.$isbn.'</dc:identifier></metadata></package>';}
try{
 $users=\OC::$server->get(\OCP\IUserManager::class);$account=$users->createUser($uid,bin2hex(random_bytes(24)));$home=\OC::$server->get(\OCP\Files\IRootFolder::class)->getUserFolder($uid);$folder=$home->newFolder('Index speed');$one=$folder->newFile('one.opf',indexOpf('Écologie alpha'));$two=$folder->newFile('two.opf',indexOpf('Second book'));
 $db=\OC::$server->get(\OCP\IDBConnection::class);$items=\OC::$server->get(\OCA\Library\Service\ItemService::class);$scanner=\OC::$server->get(\OCA\Library\Service\LibraryScanner::class);$root=\OC::$server->get(\OCA\Library\Service\RootService::class)->saveRoot($uid,'/Index speed','Index speed',true);
 $connection=libraryBenchmarkConnection();$config=$connection->getConfiguration();$original=$config->getSQLLogger();
 $row=function($file)use($db,$uid){$r=$db->executeQuery('SELECT i.* FROM *PREFIX*library_items i INNER JOIN *PREFIX*library_files f ON f.id=i.library_file_id WHERE i.user_id=? AND f.file_id=?',[$uid,$file->getId()]);$v=$r->fetch();$r->closeCursor();return $v;};
 $indexRows=function(int $id)use($db,$uid){$out=[];foreach(['library_item_facets','library_item_search_grams','library_item_identifiers'] as $table){$r=$db->executeQuery('SELECT * FROM *PREFIX*'.$table.' WHERE user_id=? AND item_id=? ORDER BY id',[$uid,$id]);$out[$table]=$r->fetchAll();$r->closeCursor();}return $out;};
 $force=function()use($db,$uid,$scanner,$root){$db->executeStatement('UPDATE *PREFIX*library_files SET metadata_extractor_revision=? WHERE user_id=?',['index-speed-force',$uid]);return $scanner->scan($uid,(int)$root['id']);};
 $first=$scanner->scan($uid,(int)$root['id']);indexCheck($first['metadataErrors']===0,'First import succeeds');$before=$row($one);$id=(int)$before['id'];indexCheck(strlen($before['scanner_index_hash'])===64,'Successful import records fingerprint');$oldIndexes=$indexRows($id);
 indexCheck(str_contains(json_encode($oldIndexes,JSON_UNESCAPED_UNICODE),'Écologie'),'Unicode facets retained');indexCheck(str_contains(json_encode($oldIndexes,JSON_UNESCAPED_UNICODE),'éco'),'Unicode search grams retained');
 $logger=new LibraryBenchmarkSql();$config->setSQLLogger($logger);try{$repeat=$force();}finally{$config->setSQLLogger($original);}indexCheck($repeat['metadataExtractions']===2,'Repeat really extracts metadata');indexCheck($indexRows($id)===$oldIndexes,'Unchanged extraction leaves index rows and IDs untouched');indexCheck($row($one)['scanner_index_hash']===$before['scanner_index_hash'],'Fingerprint stable');$writes=0;foreach($logger->groups as $g)if(preg_match('/^(INSERT|DELETE).*library_item_(facets|search_grams|identifiers)/',$g['shape']))$writes+=$g['count'];indexCheck($writes===0,'No derived index writes on identical refresh');
 $one->putContent(indexOpf('Changed beta'));$force();indexCheck($row($one)['title']==='Changed beta','Changed title refreshed');indexCheck($row($one)['scanner_index_hash']!==$before['scanner_index_hash'],'Changed input invalidates fingerprint');indexCheck($indexRows($id)!==$oldIndexes,'Changed input rebuilds indexes');
 $prior=$row($one)['scanner_index_hash'];$one->putContent(indexOpf('Changed beta','García, Ana','9780140328721'));$force();indexCheck($row($one)['scanner_index_hash']!==$prior,'Identifier changes invalidate');indexCheck(str_contains(json_encode($indexRows($id)),'9780140328721'),'Identifier index updated');
 $snapshot=$row($one);$indexes=$indexRows($id);$file=\OC::$server->get(\OCA\Library\Service\FileIndexService::class)->findByFileId($uid,$one->getId());
 $fault=new class extends LibraryBenchmarkSql {public function startQuery($sql,?array $params=null,?array $types=null){if(str_starts_with($sql,'INSERT INTO')&&str_contains($sql,'library_item_search_grams'))throw new RuntimeException('Injected index failure');parent::startQuery($sql,$params,$types);}};
 $config->setSQLLogger($fault);$rejected=false;try{$items->ensureItemForFile($uid,$file,['title'=>'Must roll back','subjects'=>['New subject'],'creators'=>'Other author','_source'=>'opf']);}catch(RuntimeException){$rejected=true;}finally{$config->setSQLLogger($original);}indexCheck($rejected,'Injected failure reached after earlier writes');indexCheck($row($one)===$snapshot,'Canonical fields and fingerprint rolled back');indexCheck($indexRows($id)===$indexes,'All derived rows rolled back');
 $legacyBefore=$indexRows($id);$db->executeStatement('UPDATE *PREFIX*library_items SET scanner_index_hash=NULL WHERE user_id=? AND id=?',[$uid,$id]);$force();indexCheck(strlen($row($one)['scanner_index_hash'])===64,'Legacy null fingerprint verified');indexCheck($indexRows($id)===$legacyBefore,'Legacy Unicode and numeric grams verified without rewriting');
 $db->executeStatement('DELETE FROM *PREFIX*library_item_search_grams WHERE user_id=? AND item_id=?',[$uid,$id]);$db->executeStatement('UPDATE *PREFIX*library_items SET scanner_index_hash=NULL WHERE user_id=? AND id=?',[$uid,$id]);$force();indexCheck(count($indexRows($id)['library_item_search_grams'])>0,'Missing legacy search rows repaired');
 $db->executeStatement('UPDATE *PREFIX*library_items SET scanner_index_hash=? WHERE user_id=? AND id=?',['old-generator',$uid,$id]);$oldIndexes=$indexRows($id);$force();indexCheck($indexRows($id)!==$oldIndexes,'Outdated generator fingerprint rebuilds');
 $oldIndexes=$indexRows($id);$db->executeStatement('UPDATE *PREFIX*library_files SET scan_status=? WHERE user_id=? AND file_id=?',['missing',$uid,$one->getId()]);$force();indexCheck($indexRows($id)!==$oldIndexes,'Returning missing publication rebuilds indexes even when fingerprint matches');
 $items->rebuildFacetIndex($uid);indexCheck($row($one)['scanner_index_hash']===null,'Explicit repair invalidates scanner fingerprint');$force();indexCheck(strlen($row($one)['scanner_index_hash'])===64,'Scan repairs invalidated derived state');
 (new ReflectionMethod($items,'invalidateScannerIndexHash'))->invoke($items,'other-user',$id);indexCheck(strlen($row($one)['scanner_index_hash'])===64,'Other account cannot invalidate fingerprint');
 $one->move($folder->getPath().'/newpath.opf');$prior=$row($one)['scanner_index_hash'];$force();indexCheck($row($one)['scanner_index_hash']!==$prior,'Moved path invalidates search/duplicate inputs');
 $items->applyBatchMetadataEdit($uid,[$id],'title','Protected correction');indexCheck($row($one)['scanner_index_hash']===null,'Manual metadata invalidates fingerprint');$one->putContent(indexOpf('New source title'));$force();indexCheck($row($one)['title']==='Protected correction','User correction survives forced refresh');
 $bytes=hash('sha256',$two->getContent());$force();indexCheck(hash('sha256',$two->getContent())===$bytes,'Source bytes unchanged by refresh');
 echo json_encode(['passed'=>true,'assertions'=>$checks,'unchangedIndexesSkipped'=>true,'unicodePreserved'=>true,'rollback'=>true,'repair'=>true,'manualCorrectionPreserved'=>true,'sourceBytesUnchanged'=>true]),PHP_EOL;
}catch(Throwable $e){$failed=true;fwrite(STDERR,get_class($e).': '.$e->getMessage().PHP_EOL);}finally{if(isset($config,$original))$config->setSQLLogger($original);if($account)$account->delete();echo json_encode(['cleanup'=>true]),PHP_EOL;}if($failed)exit(1);
